# YAML configuration file to set material properties for CPFEM
# Authors : D. Mercier and C. Zambaldi
# Give only absolute paths and put a space after the comma in a list (e.g. [x, y, z]) !!!
# Don't modify fieldnames !
# material.config for DAMASK (cp-Ti (alpha))

# Material and Constitutive Laws
Phase1_material: cpTi-alpha
Phase1_elasticity: hooke
Phase1_plasticity: phenopowerlaw

# Outputs for the constitutive Laws
Phase1_output1: resistance_slip
Phase1_output2: shearrate_slip
Phase1_output3: resolvedstress_slip
Phase1_output4: accumulatedshear_slip
Phase1_output5: totalshear
Phase1_output6: resistance_twin
Phase1_output7: shearrate_twin
Phase1_output8: resolvedstress_twin
Phase1_output9: accumulatedshear_twin
Phase1_output10: totalvolfrac

# Crystal properties
Phase1_lattice_structure: hex
# c/a ratio automatically calculated by using the Matlab file : "latt_param"
# M. Levy, Handbook of Elastic Properties of Solids, Liquids, and Gases (2001)
Phase1_c11:    160e9
Phase1_c12:    90e9
Phase1_c13:    66e9
# Phase1_c22
# Phase1_c23
Phase1_c33:    181.7e9
Phase1_c44:    46.5e9
Phase1_c66:    35e9 # =0.5*(c11-c12)

# Slip systems
# C. Zambaldi, "Orientation informed nanoindentation of a-titanium: Indentation pileup in hexagonal metals deforming by prismatic slip", J. Mater. Res., Vol. 27, No. 1, Jan 14, 2012
Phase1_nslip:  '3 3 0 6 0 0' # number of slips per family
Phase1_gdot0_slip: 0.001
Phase1_n_slip: 20
Phase1_tau0_slip: '349e6 150e6 0 1107.9e6 0 0' # per family
Phase1_tausat_slip: '568e6 1502.2e6 0 3420e6 0 0' # per family
Phase1_a_slip: 2.0

# Twin systems
Phase1_ntwin:  '0 0 0 0' # number of twins per family
Phase1_gdot0_twin: 0.001
Phase1_n_twin: 20
Phase1_tau0_twin: '31e6 0 0 0' # per family
Phase1_s_pr: 0 # push-up factor for slip saturation due to twinning
Phase1_twin_b: 0
Phase1_twin_c: 0
Phase1_twin_d: 0
Phase1_twin_e: 0
Phase1_h0_slipslip: 200.0e6
Phase1_h0_sliptwin: 0
Phase1_h0_twinslip: 0
Phase1_h0_twintwin: 0
Phase1_atol_resistance: 1
#Phase1_atol_shear: 1e-6
#Phase1_atol_twinfrac: 1e-7
Phase1_interaction_slipslip: '1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1'
Phase1_interaction_sliptwin: '1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1'
Phase1_interaction_twinslip: '1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1'
Phase1_interaction_twintwin: '1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1'